#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
حل سريع: تفعيل حساب الأدمن
نفذ هذا في Python Console على PythonAnywhere
"""

print("=" * 70)
print("تفعيل حساب الأدمن - حل سريع")
print("=" * 70)
print()
print("نفذ هذا الكود في Python Console على PythonAnywhere:")
print()
print("-" * 70)
print()
print("# استيراد المكتبات")
print("from app import create_app")
print("from models import db, Admin")
print()
print("# إنشاء التطبيق")
print("app = create_app()")
print()
print("# تنفيذ التعديلات")
print("with app.app_context():")
print("    # جلب جميع حسابات الأدمن")
print("    admins = Admin.query.all()")
print("    ")
print("    if admins:")
print("        print(f'تم العثور على {len(admins)} حساب')")
print("        ")
print("        # تفعيل جميع الحسابات")
print("        for admin in admins:")
print("            print(f'الحساب: {admin.username} - الحالة: {'نشط' if admin.is_active else 'معطل'}')")
print("            admin.is_active = True")
print("        ")
print("        db.session.commit()")
print("        print('✅ تم تفعيل جميع حسابات الأدمن بنجاح!')")
print("    else:")
print("        print('❌ لا يوجد أي حساب أدمن!')")
print()
print("-" * 70)
print()
print("بعد التنفيذ:")
print("1. جرب تسجيل الدخول مرة أخرى")
print("2. استخدم:")
print("   - اسم المستخدم: admin")
print("   - كلمة المرور: (كلمة المرور التي تعرفها)")
print()
print("=" * 70)
